const data = {
  products: [
    {
      _id:1,
      name: 'Dell 27 Monitor - S2721D',
      category: 'Monitors',
      image: '/images/p1.jpg',
      price: 178,
      countInStock: 10,
      brand: 'Dell',
      rating: 4.5,
      numReviews: 10,
      description: '27" lifestyle-inspired QHD monitor with outstanding visuals for an amazing entertainment experience.',
    },
    {
      _id:2,
      name: 'Samsung Monitor T55 27 Inch |27" ',
      category: 'Monitors',
      image: '/images/p2.jpg',
      price: 190,
      countInStock: 20,
      brand: 'Samsung',
      rating: 4.0,
      numReviews: 10,
      description: 'Next-generation design. The virtually borderless displays striking aesthetic is enhanced by a fabric-textured backside and premium-quality slim metal stand. ',
    },
    {
      _id:3,
      name: '27‑inch iMac Monitor',
      category: 'Monitors',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 17,
      description: ' 3.1GHz 6-core 10th-generation Intel Core i5 processor, Turbo Boost up to 4.5GHz ',
    },
    {
      _id:4,
      name: 'Lenovo 300 USB Keyboard',
      category: 'Keyboards',
      image: '/images/p4.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Lenovo',
      rating: 4.5,
      numReviews: 14,
      description: 'The Lenovo 300 USB keyboard offers an intuitive and comfortable island key design with 2 5 zone layout including separate number pad ',
    },
    {
      _id:5,
      name: 'Dell KB522 Business Multimedia Keyboard',
      category: 'Keyboards',
      image: '/images/p5.jpg',
      price: 30,
      countInStock: 5,
      brand: 'Dell',
      rating: 4.5,
      numReviews: 10,
      description: 'The Dell KB522 Wired Business Multimedia Keyboard has a newly refreshed ID and a sturdy/robust design with mid-profile keycap for great typing experience, quiet acoustics and durability for daily business usage. I',
    },
    {
      _id:6,
      name: 'Magic Apple Keyboard',
      category: 'Keyboards',
      image: '/images/p6.jpg',
      price: 90,
      countInStock: 12,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 15,
      description: 'Magic Keyboard delivers a remarkably comfortable and precise typing experience. Its also wireless and rechargeable, with an incredibly long-lasting internal battery that’ll power your keyboard for about a month or more between charges.',
    },
    {
      _id:7,
      name: 'Apple Magic Mouse',
      category: 'Mouse',
      image: '/images/p7.jpg',
      price: 75,
      countInStock: 12,
      brand: 'Apple',
      rating: 4,
      numReviews: 19,
      description: 'Magic Mouse is wireless and rechargeable, with an optimized foot design that lets it glide smoothly across your desk.',
    },
    {
      _id:8,
      name: 'Dell Multi-device Wireless Mouse',
      category: 'Mouse',
      image: '/images/p8.jpg',
      price: 60,
      countInStock: 12,
      brand: 'Dell',
      rating: 3.5,
      numReviews: 28,
      description: 'Work seamlessly across your desktop, laptop and 2-in-1 with this sculpted wireless mouse. The two Bluetooth 5.0 and 2.4GHz wireless connection methods allow you to switch easily across your laptop, desktop or 2-in-1 with a click of a button.',
    },
    {
      _id:9,
      name: 'Razer DeathAdder V2 Gaming Mouse',
      category: 'Mouse',
      image: '/images/p9.jpg',
      price: 55,
      countInStock: 12,
      brand: 'Razer',
      rating: 4.5,
      numReviews: 30,
      description: 'Focus+ 20K DPI Optical Sensor: Offers on-the-fly sensitivity adjustment through dedicated DPI buttons (reprogrammable) for gaming ',
    },
  ],
};
export default data;
